-- CreateEnum
CREATE TYPE "BattingStyle" AS ENUM ('RIGHT_HANDED_BATSMAN', 'LEFT_HANDED_BATSMAN');

-- CreateEnum
CREATE TYPE "BowlingStyle" AS ENUM ('RIGHT_ARM_FAST', 'RIGHT_ARM_MEDIUM_FAST', 'RIGHT_ARM_MEDIUM', 'RIGHT_ARM_SLOW_MEDIUM', 'RIGHT_ARM_SLOW', 'LEFT_ARM_FAST', 'LEFT_ARM_MEDIUM_FAST', 'LEFT_ARM_MEDIUM', 'LEFT_ARM_SLOW_MEDIUM', 'LEFT_ARM_SLOW', 'RIGHT_ARM_OFF_SPIN', 'RIGHT_ARM_LEG_SPIN', 'LEFT_ARM_OFF_SPIN', 'LEFT_ARM_LEG_SPIN');

-- AlterTable
ALTER TABLE "players" ADD COLUMN     "battingStyle" "BattingStyle",
ADD COLUMN     "birthDate" TIMESTAMP(3),
ADD COLUMN     "bowlingStyle" "BowlingStyle",
ADD COLUMN     "city" TEXT,
ADD COLUMN     "state" TEXT;
