import {
  MatchFormat,
  MatchStatus,
  TossDecision,
} from "../../src/generated/prisma/enums.js";

export type matchType = {
  id: string;
  tournamentId: string;
  title: string;
  slug: string;
  matchFormat: MatchFormat;
  status: MatchStatus;
  matchDate: Date;
  venue: string | null;
  city: string | null;
  homeTeamId: string;
  awayTeamId: string;
  tossWinnerTeamId: string | null;
  tossDecision: TossDecision | null;
};

const getFutureDate = (
  daysAhead: number,
  hours: number = 19,
  minutes: number = 30,
): Date => {
  const date = new Date();
  date.setDate(date.getDate() + daysAhead);
  date.setHours(hours, minutes, 0, 0);
  return date;
};

const matches: matchType[] = [
  // 1. India vs England
  {
    id: "201",
    tournamentId: "tour-1",
    title: "India vs England - T10",
    slug: "india-vs-england-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-01"),
    venue: "Lord's",
    city: "London",
    homeTeamId: "102",
    awayTeamId: "101",
    tossWinnerTeamId: "101",
    tossDecision: TossDecision.BAT,
  },
  // 2. India vs Australia
  {
    id: "202",
    tournamentId: "tour-1",
    title: "India vs Australia - T10",
    slug: "india-vs-australia-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-03"),
    venue: "Narendra Modi Stadium",
    city: "Ahmedabad",
    homeTeamId: "101",
    awayTeamId: "103",
    tossWinnerTeamId: "101",
    tossDecision: TossDecision.BOWL,
  },
  // 3. India vs New Zealand
  {
    id: "203",
    tournamentId: "tour-1",
    title: "India vs New Zealand - T10",
    slug: "india-vs-new-zealand-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-05"),
    venue: "Wankhede Stadium",
    city: "Mumbai",
    homeTeamId: "101",
    awayTeamId: "104",
    tossWinnerTeamId: "104",
    tossDecision: TossDecision.BAT,
  },
  // 4. India vs Sri Lanka
  {
    id: "204",
    tournamentId: "tour-1",
    title: "India vs Sri Lanka - T10",
    slug: "india-vs-sri-lanka-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-07"),
    venue: "Eden Gardens",
    city: "Kolkata",
    homeTeamId: "101",
    awayTeamId: "105",
    tossWinnerTeamId: "101",
    tossDecision: TossDecision.BAT,
  },
  // 5. India vs South Africa
  {
    id: "205",
    tournamentId: "tour-1",
    title: "India vs South Africa - T10",
    slug: "india-vs-south-africa-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-09"),
    venue: "M. Chinnaswamy Stadium",
    city: "Bengaluru",
    homeTeamId: "101",
    awayTeamId: "106",
    tossWinnerTeamId: "106",
    tossDecision: TossDecision.BOWL,
  },
  // 6. India vs West Indies
  {
    id: "206",
    tournamentId: "tour-1",
    title: "India vs West Indies - T10",
    slug: "india-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-11"),
    venue: "Narendra Modi Stadium",
    city: "Ahmedabad",
    homeTeamId: "101",
    awayTeamId: "107",
    tossWinnerTeamId: "101",
    tossDecision: TossDecision.BAT,
  },
  // 7. India vs Ireland
  {
    id: "207",
    tournamentId: "tour-1",
    title: "India vs Ireland - T10",
    slug: "india-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-13"),
    venue: "Wankhede Stadium",
    city: "Mumbai",
    homeTeamId: "101",
    awayTeamId: "108",
    tossWinnerTeamId: "101",
    tossDecision: TossDecision.BOWL,
  },

  // 8. England vs Australia
  {
    id: "208",
    tournamentId: "tour-1",
    title: "England vs Australia - T10",
    slug: "england-vs-australia-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-15"),
    venue: "The Oval",
    city: "London",
    homeTeamId: "102",
    awayTeamId: "103",
    tossWinnerTeamId: "103",
    tossDecision: TossDecision.BAT,
  },
  // 9. England vs New Zealand
  {
    id: "209",
    tournamentId: "tour-1",
    title: "England vs New Zealand - T10",
    slug: "england-vs-new-zealand-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-17"),
    venue: "Edgbaston",
    city: "Birmingham",
    homeTeamId: "102",
    awayTeamId: "104",
    tossWinnerTeamId: "102",
    tossDecision: TossDecision.BOWL,
  },
  // 10. England vs Sri Lanka
  {
    id: "210",
    tournamentId: "tour-1",
    title: "England vs Sri Lanka - T10",
    slug: "england-vs-sri-lanka-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-19"),
    venue: "Headingley",
    city: "Leeds",
    homeTeamId: "102",
    awayTeamId: "105",
    tossWinnerTeamId: "102",
    tossDecision: TossDecision.BAT,
  },
  // 11. England vs South Africa
  {
    id: "211",
    tournamentId: "tour-1",
    title: "England vs South Africa - T10",
    slug: "england-vs-south-africa-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-21"),
    venue: "Lord's",
    city: "London",
    homeTeamId: "102",
    awayTeamId: "106",
    tossWinnerTeamId: "106",
    tossDecision: TossDecision.BOWL,
  },
  // 12. England vs West Indies
  {
    id: "212",
    tournamentId: "tour-1",
    title: "England vs West Indies - T10",
    slug: "england-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-23"),
    venue: "The Oval",
    city: "London",
    homeTeamId: "102",
    awayTeamId: "107",
    tossWinnerTeamId: "107",
    tossDecision: TossDecision.BAT,
  },
  // 13. England vs Ireland
  {
    id: "213",
    tournamentId: "tour-1",
    title: "England vs Ireland - T10",
    slug: "england-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-25"),
    venue: "Malahide Cricket Club Ground",
    city: "Dublin",
    homeTeamId: "108",
    awayTeamId: "102",
    tossWinnerTeamId: "102",
    tossDecision: TossDecision.BOWL,
  },

  // 14. Australia vs New Zealand
  {
    id: "214",
    tournamentId: "tour-1",
    title: "Australia vs New Zealand - T10",
    slug: "australia-vs-new-zealand-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-27"),
    venue: "Melbourne Cricket Ground",
    city: "Melbourne",
    homeTeamId: "103",
    awayTeamId: "104",
    tossWinnerTeamId: "103",
    tossDecision: TossDecision.BAT,
  },
  // 15. Australia vs Sri Lanka
  {
    id: "215",
    tournamentId: "tour-1",
    title: "Australia vs Sri Lanka - T10",
    slug: "australia-vs-sri-lanka-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-29"),
    venue: "Sydney Cricket Ground",
    city: "Sydney",
    homeTeamId: "103",
    awayTeamId: "105",
    tossWinnerTeamId: "103",
    tossDecision: TossDecision.BOWL,
  },
  // 16. Australia vs South Africa
  {
    id: "216",
    tournamentId: "tour-1",
    title: "Australia vs South Africa - T10",
    slug: "australia-vs-south-africa-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-07-31"),
    venue: "Adelaide Oval",
    city: "Adelaide",
    homeTeamId: "103",
    awayTeamId: "106",
    tossWinnerTeamId: "106",
    tossDecision: TossDecision.BAT,
  },
  // 17. Australia vs West Indies
  {
    id: "217",
    tournamentId: "tour-1",
    title: "Australia vs West Indies - T10",
    slug: "australia-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-08-02"),
    venue: "The Gabba",
    city: "Brisbane",
    homeTeamId: "103",
    awayTeamId: "107",
    tossWinnerTeamId: "103",
    tossDecision: TossDecision.BOWL,
  },
  // 18. Australia vs Ireland
  {
    id: "218",
    tournamentId: "tour-1",
    title: "Australia vs Ireland - T10",
    slug: "australia-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-08-04"),
    venue: "Melbourne Cricket Ground",
    city: "Melbourne",
    homeTeamId: "103",
    awayTeamId: "108",
    tossWinnerTeamId: "103",
    tossDecision: TossDecision.BAT,
  },

  // 19. New Zealand vs Sri Lanka
  {
    id: "219",
    tournamentId: "tour-1",
    title: "New Zealand vs Sri Lanka - T10",
    slug: "new-zealand-vs-sri-lanka-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-08-06"),
    venue: "Eden Park",
    city: "Auckland",
    homeTeamId: "104",
    awayTeamId: "105",
    tossWinnerTeamId: "104",
    tossDecision: TossDecision.BOWL,
  },
  // 20. New Zealand vs South Africa
  {
    id: "220",
    tournamentId: "tour-1",
    title: "New Zealand vs South Africa - T10",
    slug: "new-zealand-vs-south-africa-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-08-08"),
    venue: "Basin Reserve",
    city: "Wellington",
    homeTeamId: "104",
    awayTeamId: "106",
    tossWinnerTeamId: "106",
    tossDecision: TossDecision.BAT,
  },
  // 21. New Zealand vs West Indies
  {
    id: "221",
    tournamentId: "tour-1",
    title: "New Zealand vs West Indies - T10",
    slug: "new-zealand-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.COMPLETED,
    matchDate: new Date("2026-08-10"),
    venue: "Hagley Oval",
    city: "Christchurch",
    homeTeamId: "104",
    awayTeamId: "107",
    tossWinnerTeamId: "104",
    tossDecision: TossDecision.BAT,
  },
  // 22. New Zealand vs Ireland
  {
    id: "222",
    tournamentId: "tour-1",
    title: "New Zealand vs Ireland - T10",
    slug: "new-zealand-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(1, 14, 0),
    venue: "Seddon Park",
    city: "Hamilton",
    homeTeamId: "104",
    awayTeamId: "108",
    tossWinnerTeamId: null,
    tossDecision: null,
  },

  // 23. Sri Lanka vs South Africa
  {
    id: "223",
    tournamentId: "tour-1",
    title: "Sri Lanka vs South Africa - T10",
    slug: "sri-lanka-vs-south-africa-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(2, 19, 30),
    venue: "R. Premadasa Stadium",
    city: "Colombo",
    homeTeamId: "105",
    awayTeamId: "106",
    tossWinnerTeamId: null,
    tossDecision: null,
  },
  // 24. Sri Lanka vs West Indies
  {
    id: "224",
    tournamentId: "tour-1",
    title: "Sri Lanka vs West Indies - T10",
    slug: "sri-lanka-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(3, 19, 30),
    venue: "Pallekele International Cricket Stadium",
    city: "Kandy",
    homeTeamId: "105",
    awayTeamId: "107",
    tossWinnerTeamId: null,
    tossDecision: null,
  },
  // 25. Sri Lanka vs Ireland
  {
    id: "225",
    tournamentId: "tour-1",
    title: "Sri Lanka vs Ireland - T10",
    slug: "sri-lanka-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(4, 15, 30),
    venue: "Galle International Stadium",
    city: "Galle",
    homeTeamId: "105",
    awayTeamId: "108",
    tossWinnerTeamId: null,
    tossDecision: null,
  },

  // 26. South Africa vs West Indies
  {
    id: "226",
    tournamentId: "tour-1",
    title: "South Africa vs West Indies - T10",
    slug: "south-africa-vs-west-indies-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(5, 19, 30),
    venue: "Wanderers Stadium",
    city: "Johannesburg",
    homeTeamId: "106",
    awayTeamId: "107",
    tossWinnerTeamId: null,
    tossDecision: null,
  },
  // 27. South Africa vs Ireland
  {
    id: "227",
    tournamentId: "tour-1",
    title: "South Africa vs Ireland - T10",
    slug: "south-africa-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(6, 19, 30),
    venue: "Newlands Cricket Ground",
    city: "Cape Town",
    homeTeamId: "106",
    awayTeamId: "108",
    tossWinnerTeamId: null,
    tossDecision: null,
  },

  // 28. West Indies vs Ireland
  {
    id: "228",
    tournamentId: "tour-1",
    title: "West Indies vs Ireland - T10",
    slug: "west-indies-vs-ireland-t10",
    matchFormat: MatchFormat.T10,
    status: MatchStatus.UPCOMING,
    matchDate: getFutureDate(7, 20, 0),
    venue: "Kensington Oval",
    city: "Bridgetown",
    homeTeamId: "107",
    awayTeamId: "108",
    tossWinnerTeamId: null,
    tossDecision: null,
  },
];

export default matches;
