import { PlayerRole } from "../../src/generated/prisma/enums.js";

type playerType = {
  id: string;
  playerName: string;
  displayName: string | null;
  slug: string;
  photoUrl: string | null;
  role: PlayerRole;
  canKeepWickets: boolean;
};

const players: playerType[] = [
  // ========== India ==========

  {
    id: "1",
    playerName: "Rohit Sharma",
    displayName: "R Sharma",
    slug: "rohit-sharma",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "2",
    playerName: "Shikhar Dhawan",
    displayName: "S Dhawan",
    slug: "shikhar-dhawan",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "3",
    playerName: "Virat Kohli",
    displayName: "V Kohli",
    slug: "virat-kohli",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "4",
    playerName: "KL Rahul",
    displayName: "KL Rahul",
    slug: "kl-rahul",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
  },
  {
    id: "5",
    playerName: "Shreyas Iyer",
    displayName: "S Iyer",
    slug: "shreyas-iyer",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "6",
    playerName: "Mahendra Singh Dhoni",
    displayName: "MS Dhoni",
    slug: "mahendra-singh-dhoni",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
  },
  {
    id: "7",
    playerName: "Ravindra Jadeja",
    displayName: "R Jadeja",
    slug: "ravindra-jadeja",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "8",
    playerName: "Axar Patel",
    displayName: "A Patel",
    slug: "axar-patel",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "9",
    playerName: "Ravichandran Ashwin",
    displayName: "R Ashwin",
    slug: "ravichandran-ashwin",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "10",
    playerName: "Jasprit Bumrah",
    displayName: "J Bumrah",
    slug: "jasprit-bumrah",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
  {
    id: "11",
    playerName: "Bhuvneshwar Kumar",
    displayName: "B Kumar",
    slug: "bhuvneshwar-kumar",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
  {
    id: "12",
    playerName: "Mohammed Shami",
    displayName: "M Shami",
    slug: "mohammed-shami",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
  {
    id: "13",
    playerName: "Kuldeep Yadav",
    displayName: "K Yadav",
    slug: "kuldeep-yadav",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },

  // ========== England ==========

  {
    id: "14",
    playerName: "Phil Salt",
    displayName: "P Salt",
    slug: "phil-salt",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "15",
    playerName: "Jos Buttler",
    displayName: "J Buttler",
    slug: "jos-buttler",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
  },
  {
    id: "16",
    playerName: "Harry Brook",
    displayName: "H Brook",
    slug: "harry-brook",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "17",
    playerName: "Jacob Bethell",
    displayName: "J Bethell",
    slug: "jacob-bethell",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "18",
    playerName: "Harry Brook",
    displayName: "H Brook",
    slug: "harry-brook",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
  },
  {
    id: "19",
    playerName: "Will Jacks",
    displayName: "W Jacks",
    slug: "will-jacks",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "20",
    playerName: "Ben Stokes",
    displayName: "B Stokes",
    slug: "ben-stokes",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "21",
    playerName: "Sam Curran",
    displayName: "S Curran",
    slug: "sam-curran",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "22",
    playerName: "Moeen Ali",
    displayName: "Moeen Ali",
    slug: "moeen-ali",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
  },
  {
    id: "23",
    playerName: "Jofra Archer",
    displayName: "J Archer",
    slug: "jofra-archer",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
  {
    id: "24",
    playerName: "Mark Wood",
    displayName: "M Wood",
    slug: "mark-wood",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
  {
    id: "25",
    playerName: "Chris Woakes",
    displayName: "C Woakes",
    slug: "chris-woakes",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
  },
];

export default players;
