import {
  BattingStyle,
  BowlingStyle,
  PlayerRole,
} from "../../src/generated/prisma/enums.js";

export type playerType = {
  id: string;
  userId: string;
  name: string;
  displayName: string | null;
  slug: string;
  photoUrl: string | null;
  role: PlayerRole;
  canKeepWickets: boolean;
  battingStyle: BattingStyle;
  bowlingStyle: BowlingStyle;
  city: string;
  state: string;
  birthDate: string;
};

const players: playerType[] = [
  // ========== India ==========

  {
    id: "1",
    userId: "user-1",
    name: "Rohit Sharma",
    displayName: "R Sharma",
    slug: "rohit-sharma",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Mumbai",
    state: "Maharashtra",
    birthDate: "1987-04-30",
  },
  {
    id: "2",
    userId: "user-2",
    name: "Shikhar Dhawan",
    displayName: "S Dhawan",
    slug: "shikhar-dhawan",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Delhi",
    state: "Delhi",
    birthDate: "1985-12-05",
  },
  {
    id: "3",
    userId: "user-3",
    name: "Virat Kohli",
    displayName: "V Kohli",
    slug: "virat-kohli",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Delhi",
    state: "Delhi",
    birthDate: "1988-11-05",
  },
  {
    id: "4",
    userId: "user-4",
    name: "KL Rahul",
    displayName: "KL Rahul",
    slug: "kl-rahul",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Mangalore",
    state: "Karnataka",
    birthDate: "1992-04-18",
  },
  {
    id: "5",
    userId: "user-5",
    name: "Shreyas Iyer",
    displayName: "S Iyer",
    slug: "shreyas-iyer",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Mumbai",
    state: "Maharashtra",
    birthDate: "1994-12-06",
  },
  {
    id: "6",
    userId: "user-6",
    name: "Mahendra Singh Dhoni",
    displayName: "MS Dhoni",
    slug: "mahendra-singh-dhoni",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Ranchi",
    state: "Jharkhand",
    birthDate: "1981-07-07",
  },
  {
    id: "7",
    userId: "user-7",
    name: "Ravindra Jadeja",
    displayName: "R Jadeja",
    slug: "ravindra-jadeja",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Navagam",
    state: "Gujarat",
    birthDate: "1988-12-02",
  },
  {
    id: "8",
    userId: "user-8",
    name: "Axar Patel",
    displayName: "A Patel",
    slug: "axar-patel",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Nadiad",
    state: "Gujarat",
    birthDate: "1994-01-20",
  },
  {
    id: "9",
    userId: "user-9",
    name: "Ravichandran Ashwin",
    displayName: "R Ashwin",
    slug: "ravichandran-ashwin",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Chennai",
    state: "Tamil Nadu",
    birthDate: "1986-09-17",
  },
  {
    id: "10",
    userId: "user-10",
    name: "Jasprit Bumrah",
    displayName: "J Bumrah",
    slug: "jasprit-bumrah",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Ahmedabad",
    state: "Gujarat",
    birthDate: "1993-12-06",
  },
  {
    id: "11",
    userId: "user-11",
    name: "Bhuvneshwar Kumar",
    displayName: "B Kumar",
    slug: "bhuvneshwar-kumar",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Meerut",
    state: "Uttar Pradesh",
    birthDate: "1990-02-05",
  },
  {
    id: "12",
    userId: "user-12",
    name: "Mohammed Shami",
    displayName: "M Shami",
    slug: "mohammed-shami",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Amroha",
    state: "Uttar Pradesh",
    birthDate: "1990-09-03",
  },
  {
    id: "13",
    userId: "user-13",
    name: "Kuldeep Yadav",
    displayName: "K Yadav",
    slug: "kuldeep-yadav",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_LEG_SPIN,
    city: "Kanpur",
    state: "Uttar Pradesh",
    birthDate: "1994-12-14",
  },

  // ========== England ==========

  {
    id: "14",
    userId: "user-14",
    name: "Phil Salt",
    displayName: "P Salt",
    slug: "phil-salt",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Bodelwyddan",
    state: "Wales",
    birthDate: "1996-08-28",
  },
  {
    id: "15",
    userId: "user-15",
    name: "Jos Buttler",
    displayName: "J Buttler",
    slug: "jos-buttler",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Taunton",
    state: "Somerset",
    birthDate: "1990-09-08",
  },
  {
    id: "16",
    userId: "user-16",
    name: "Joe Root",
    displayName: "J Root",
    slug: "joe-root",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Sheffield",
    state: "Yorkshire",
    birthDate: "1990-12-30",
  },
  {
    id: "17",
    userId: "user-17",
    name: "Jacob Bethell",
    displayName: "J Bethell",
    slug: "jacob-bethell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Bridgetown",
    state: "Barbados",
    birthDate: "2003-10-23",
  },
  {
    id: "18",
    userId: "user-18",
    name: "Harry Brook",
    displayName: "H Brook",
    slug: "harry-brook",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Keighley",
    state: "Yorkshire",
    birthDate: "1999-02-22",
  },
  {
    id: "19",
    userId: "user-19",
    name: "Will Jacks",
    displayName: "W Jacks",
    slug: "will-jacks",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Chertsey",
    state: "Surrey",
    birthDate: "1998-11-21",
  },
  {
    id: "20",
    userId: "user-20",
    name: "Ben Stokes",
    displayName: "B Stokes",
    slug: "ben-stokes",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Christchurch",
    state: "Durham",
    birthDate: "1991-06-04",
  },
  {
    id: "21",
    userId: "user-21",
    name: "Sam Curran",
    displayName: "S Curran",
    slug: "sam-curran",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM_FAST,
    city: "Northampton",
    state: "Surrey",
    birthDate: "1998-06-03",
  },
  {
    id: "22",
    userId: "user-22",
    name: "Moeen Ali",
    displayName: "M Ali",
    slug: "moeen-ali",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Birmingham",
    state: "Warwickshire",
    birthDate: "1987-06-18",
  },
  {
    id: "23",
    userId: "user-23",
    name: "Jofra Archer",
    displayName: "J Archer",
    slug: "jofra-archer",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Bridgetown",
    state: "Sussex",
    birthDate: "1995-04-01",
  },
  {
    id: "24",
    userId: "user-24",
    name: "Mark Wood",
    displayName: "M Wood",
    slug: "mark-wood",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Ashington",
    state: "Northumberland",
    birthDate: "1990-01-11",
  },
  {
    id: "25",
    userId: "user-25",
    name: "Chris Woakes",
    displayName: "C Woakes",
    slug: "chris-woakes",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Birmingham",
    state: "Warwickshire",
    birthDate: "1989-03-02",
  },

  // ========== Australia ==========

  {
    id: "26",
    userId: "user-26",
    name: "Pat Cummins",
    displayName: "P Cummins",
    slug: "pat-cummins",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Westmead",
    state: "New South Wales",
    birthDate: "1993-05-08",
  },
  {
    id: "27",
    userId: "user-27",
    name: "Travis Head",
    displayName: "T Head",
    slug: "travis-head",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Adelaide",
    state: "South Australia",
    birthDate: "1993-12-29",
  },
  {
    id: "28",
    userId: "user-28",
    name: "David Warner",
    displayName: "D Warner",
    slug: "david-warner",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Paddington",
    state: "New South Wales",
    birthDate: "1986-10-27",
  },
  {
    id: "29",
    userId: "user-29",
    name: "Steven Smith",
    displayName: "S Smith",
    slug: "steven-smith",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Sydney",
    state: "New South Wales",
    birthDate: "1989-06-02",
  },
  {
    id: "30",
    userId: "user-30",
    name: "Marnus Labuschagne",
    displayName: "M Labuschagne",
    slug: "marnus-labuschagne",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Klerksdorp",
    state: "Queensland",
    birthDate: "1994-06-22",
  },
  {
    id: "31",
    userId: "user-31",
    name: "Mitchell Marsh",
    displayName: "M Marsh",
    slug: "mitchell-marsh",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Perth",
    state: "Western Australia",
    birthDate: "1991-10-20",
  },
  {
    id: "32",
    userId: "user-32",
    name: "Glenn Maxwell",
    displayName: "G Maxwell",
    slug: "glenn-maxwell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Kew",
    state: "Victoria",
    birthDate: "1988-10-14",
  },
  {
    id: "33",
    userId: "user-33",
    name: "Alex Carey",
    displayName: "A Carey",
    slug: "alex-carey",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Loxton",
    state: "South Australia",
    birthDate: "1991-08-27",
  },
  {
    id: "34",
    userId: "user-34",
    name: "Josh Inglis",
    displayName: "J Inglis",
    slug: "josh-inglis",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Leeds",
    state: "Western Australia",
    birthDate: "1995-03-04",
  },
  {
    id: "35",
    userId: "user-35",
    name: "Marcus Stoinis",
    displayName: "M Stoinis",
    slug: "marcus-stoinis",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Perth",
    state: "Western Australia",
    birthDate: "1989-08-16",
  },
  {
    id: "36",
    userId: "user-36",
    name: "Mitchell Starc",
    displayName: "M Starc",
    slug: "mitchell-starc",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_FAST,
    city: "Baulkham Hills",
    state: "New South Wales",
    birthDate: "1990-01-30",
  },
  {
    id: "37",
    userId: "user-37",
    name: "Josh Hazlewood",
    displayName: "J Hazlewood",
    slug: "josh-hazlewood",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Tamworth",
    state: "New South Wales",
    birthDate: "1991-01-08",
  },
  {
    id: "38",
    userId: "user-38",
    name: "Adam Zampa",
    displayName: "A Zampa",
    slug: "adam-zampa",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Shellharbour",
    state: "New South Wales",
    birthDate: "1992-03-31",
  },

  // ========== New Zealand ==========

  {
    id: "39",
    userId: "user-39",
    name: "Kane Williamson",
    displayName: "K Williamson",
    slug: "kane-williamson",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Tauranga",
    state: "Bay of Plenty",
    birthDate: "1990-08-08",
  },
  {
    id: "40",
    userId: "user-40",
    name: "Devon Conway",
    displayName: "D Conway",
    slug: "devon-conway",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Johannesburg",
    state: "Wellington",
    birthDate: "1991-07-08",
  },
  {
    id: "41",
    userId: "user-41",
    name: "Rachin Ravindra",
    displayName: "R Ravindra",
    slug: "rachin-ravindra",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Wellington",
    state: "Wellington",
    birthDate: "1999-11-18",
  },
  {
    id: "42",
    userId: "user-42",
    name: "Daryl Mitchell",
    displayName: "D Mitchell",
    slug: "daryl-mitchell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Hamilton",
    state: "Waikato",
    birthDate: "1991-05-20",
  },
  {
    id: "43",
    userId: "user-43",
    name: "Tom Latham",
    displayName: "T Latham",
    slug: "tom-latham",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Christchurch",
    state: "Canterbury",
    birthDate: "1992-04-02",
  },
  {
    id: "44",
    userId: "user-44",
    name: "Glenn Phillips",
    displayName: "G Phillips",
    slug: "glenn-phillips",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "East London",
    state: "Otago",
    birthDate: "1996-12-06",
  },
  {
    id: "45",
    userId: "user-45",
    name: "Mitchell Santner",
    displayName: "M Santner",
    slug: "mitchell-santner",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Hamilton",
    state: "Northern Districts",
    birthDate: "1992-02-05",
  },
  {
    id: "46",
    userId: "user-46",
    name: "Mark Chapman",
    displayName: "M Chapman",
    slug: "mark-chapman",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Hong Kong",
    state: "Auckland",
    birthDate: "1994-06-27",
  },
  {
    id: "47",
    userId: "user-47",
    name: "Trent Boult",
    displayName: "T Boult",
    slug: "trent-boult",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_FAST,
    city: "Rotorua",
    state: "Bay of Plenty",
    birthDate: "1989-07-22",
  },
  {
    id: "48",
    userId: "user-48",
    name: "Tim Southee",
    displayName: "T Southee",
    slug: "tim-southee",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Whangarei",
    state: "Northland",
    birthDate: "1988-12-11",
  },
  {
    id: "49",
    userId: "user-49",
    name: "Matt Henry",
    displayName: "M Henry",
    slug: "matt-henry",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Christchurch",
    state: "Canterbury",
    birthDate: "1991-12-14",
  },
  {
    id: "50",
    userId: "user-50",
    name: "Lockie Ferguson",
    displayName: "L Ferguson",
    slug: "lockie-ferguson",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Auckland",
    state: "Auckland",
    birthDate: "1991-06-13",
  },
  {
    id: "51",
    userId: "user-51",
    name: "Ish Sodhi",
    displayName: "I Sodhi",
    slug: "ish-sodhi",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Ludhiana",
    state: "Northern Districts",
    birthDate: "1992-10-31",
  },

  // ========== Sri Lanka ==========

  {
    id: "52",
    userId: "user-52",
    name: "Pathum Nissanka",
    displayName: "P Nissanka",
    slug: "pathum-nissanka",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Galle",
    state: "Southern Province",
    birthDate: "1998-05-18",
  },
  {
    id: "53",
    userId: "user-53",
    name: "Kusal Mendis",
    displayName: "K Mendis",
    slug: "kusal-mendis",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Moratuwa",
    state: "Western Province",
    birthDate: "1995-02-02",
  },
  {
    id: "54",
    userId: "user-54",
    name: "Charith Asalanka",
    displayName: "C Asalanka",
    slug: "charith-asalanka",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Elpitiya",
    state: "Southern Province",
    birthDate: "1997-06-29",
  },
  {
    id: "55",
    userId: "user-55",
    name: "Kusal Perera",
    displayName: "K Perera",
    slug: "kusal-perera",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Kalubowila",
    state: "Western Province",
    birthDate: "1990-08-17",
  },
  {
    id: "56",
    userId: "user-56",
    name: "Dasun Shanaka",
    displayName: "D Shanaka",
    slug: "dasun-shanaka",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Negombo",
    state: "Western Province",
    birthDate: "1991-09-09",
  },
  {
    id: "57",
    userId: "user-57",
    name: "Wanindu Hasaranga",
    displayName: "W Hasaranga",
    slug: "wanindu-hasaranga",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Galle",
    state: "Southern Province",
    birthDate: "1997-07-29",
  },
  {
    id: "58",
    userId: "user-58",
    name: "Angelo Mathews",
    displayName: "A Mathews",
    slug: "angelo-mathews",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Colombo",
    state: "Western Province",
    birthDate: "1987-06-02",
  },
  {
    id: "59",
    userId: "user-59",
    name: "Dhananjaya de Silva",
    displayName: "D de Silva",
    slug: "dhananjaya-de-silva",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Colombo",
    state: "Western Province",
    birthDate: "1991-09-06",
  },
  {
    id: "60",
    userId: "user-60",
    name: "Maheesh Theekshana",
    displayName: "M Theekshana",
    slug: "maheesh-theekshana",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Colombo",
    state: "Western Province",
    birthDate: "2000-08-01",
  },
  {
    id: "61",
    userId: "user-61",
    name: "Matheesha Pathirana",
    displayName: "M Pathirana",
    slug: "matheesha-pathirana",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Kandy",
    state: "Central Province",
    birthDate: "2002-12-18",
  },
  {
    id: "62",
    userId: "user-62",
    name: "Dilshan Madushanka",
    displayName: "D Madushanka",
    slug: "dilshan-madushanka",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_FAST,
    city: "Hambantota",
    state: "Southern Province",
    birthDate: "2000-09-18",
  },
  {
    id: "63",
    userId: "user-63",
    name: "Kasun Rajitha",
    displayName: "K Rajitha",
    slug: "kasun-rajitha",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Matara",
    state: "Southern Province",
    birthDate: "1993-06-01",
  },
  {
    id: "64",
    userId: "user-64",
    name: "Dunith Wellalage",
    displayName: "D Wellalage",
    slug: "dunith-wellalage",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Colombo",
    state: "Western Province",
    birthDate: "2003-01-09",
  },

  // ========== South Africa ==========

  {
    id: "65",
    userId: "user-65",
    name: "Temba Bavuma",
    displayName: "T Bavuma",
    slug: "temba-bavuma",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Cape Town",
    state: "Western Cape",
    birthDate: "1990-05-17",
  },
  {
    id: "66",
    userId: "user-66",
    name: "Quinton de Kock",
    displayName: "Q de Kock",
    slug: "quinton-de-kock",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Johannesburg",
    state: "Gauteng",
    birthDate: "1992-12-17",
  },
  {
    id: "67",
    userId: "user-67",
    name: "Aiden Markram",
    displayName: "A Markram",
    slug: "aiden-markram",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Centurion",
    state: "Gauteng",
    birthDate: "1994-10-04",
  },
  {
    id: "68",
    userId: "user-68",
    name: "Heinrich Klaasen",
    displayName: "H Klaasen",
    slug: "heinrich-klaasen",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Pretoria",
    state: "Gauteng",
    birthDate: "1991-07-30",
  },
  {
    id: "69",
    userId: "user-69",
    name: "David Miller",
    displayName: "D Miller",
    slug: "david-miller",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Pietermaritzburg",
    state: "KwaZulu-Natal",
    birthDate: "1989-06-10",
  },
  {
    id: "70",
    userId: "user-70",
    name: "Rassie van der Dussen",
    displayName: "R van der Dussen",
    slug: "rassie-van-der-dussen",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Pretoria",
    state: "Gauteng",
    birthDate: "1989-02-07",
  },
  {
    id: "71",
    userId: "user-71",
    name: "Marco Jansen",
    displayName: "M Jansen",
    slug: "marco-jansen",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_FAST,
    city: "Klerksdorp",
    state: "North West",
    birthDate: "2000-05-01",
  },
  {
    id: "72",
    userId: "user-72",
    name: "Kagiso Rabada",
    displayName: "K Rabada",
    slug: "kagiso-rabada",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Johannesburg",
    state: "Gauteng",
    birthDate: "1995-05-25",
  },
  {
    id: "73",
    userId: "user-73",
    name: "Anrich Nortje",
    displayName: "A Nortje",
    slug: "anrich-nortje",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Uitenhage",
    state: "Eastern Cape",
    birthDate: "1993-11-04",
  },
  {
    id: "74",
    userId: "user-74",
    name: "Keshav Maharaj",
    displayName: "K Maharaj",
    slug: "keshav-maharaj",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Durban",
    state: "KwaZulu-Natal",
    birthDate: "1990-02-07",
  },
  {
    id: "75",
    userId: "user-75",
    name: "Tabraiz Shamsi",
    displayName: "T Shamsi",
    slug: "tabraiz-shamsi",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_LEG_SPIN,
    city: "Johannesburg",
    state: "Gauteng",
    birthDate: "1990-02-18",
  },
  {
    id: "76",
    userId: "user-76",
    name: "Lungi Ngidi",
    displayName: "L Ngidi",
    slug: "lungi-ngidi",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Durban",
    state: "KwaZulu-Natal",
    birthDate: "1996-03-29",
  },
  {
    id: "77",
    userId: "user-77",
    name: "Tristan Stubbs",
    displayName: "T Stubbs",
    slug: "tristan-stubbs",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Johannesburg",
    state: "Eastern Cape",
    birthDate: "2000-08-14",
  },

  // ========== West Indies ==========

  {
    id: "78",
    userId: "user-78",
    name: "Shai Hope",
    displayName: "S Hope",
    slug: "shai-hope",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Saint Michael",
    state: "Barbados",
    birthDate: "1993-11-10",
  },
  {
    id: "79",
    userId: "user-79",
    name: "Nicholas Pooran",
    displayName: "N Pooran",
    slug: "nicholas-pooran",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Couva",
    state: "Trinidad and Tobago",
    birthDate: "1995-10-02",
  },
  {
    id: "80",
    userId: "user-80",
    name: "Rovman Powell",
    displayName: "R Powell",
    slug: "rovman-powell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Kingston",
    state: "Jamaica",
    birthDate: "1993-07-23",
  },
  {
    id: "81",
    userId: "user-81",
    name: "Shimron Hetmyer",
    displayName: "S Hetmyer",
    slug: "shimron-hetmyer",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Cumberland",
    state: "Guyana",
    birthDate: "1996-12-26",
  },
  {
    id: "82",
    userId: "user-82",
    name: "Brandon King",
    displayName: "B King",
    slug: "brandon-king",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Kingston",
    state: "Jamaica",
    birthDate: "1994-12-16",
  },
  {
    id: "83",
    userId: "user-83",
    name: "Kyle Mayers",
    displayName: "K Mayers",
    slug: "kyle-mayers",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Bridgetown",
    state: "Barbados",
    birthDate: "1992-09-08",
  },
  {
    id: "84",
    userId: "user-84",
    name: "Andre Russell",
    displayName: "A Russell",
    slug: "andre-russell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Kingston",
    state: "Jamaica",
    birthDate: "1988-04-29",
  },
  {
    id: "85",
    userId: "user-85",
    name: "Jason Holder",
    displayName: "J Holder",
    slug: "jason-holder",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Bridgetown",
    state: "Barbados",
    birthDate: "1991-11-05",
  },
  {
    id: "86",
    userId: "user-86",
    name: "Romario Shepherd",
    displayName: "R Shepherd",
    slug: "romario-shepherd",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Berbice",
    state: "Guyana",
    birthDate: "1994-11-26",
  },
  {
    id: "87",
    userId: "user-87",
    name: "Alzarri Joseph",
    displayName: "A Joseph",
    slug: "alzarri-joseph",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Antigua",
    state: "Antigua and Barbuda",
    birthDate: "1996-11-20",
  },
  {
    id: "88",
    userId: "user-88",
    name: "Akeal Hosein",
    displayName: "A Hosein",
    slug: "akeal-hosein",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Port of Spain",
    state: "Trinidad and Tobago",
    birthDate: "1993-04-25",
  },
  {
    id: "89",
    userId: "user-89",
    name: "Gudakesh Motie",
    displayName: "G Motie",
    slug: "gudakesh-motie",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Berbice",
    state: "Guyana",
    birthDate: "1995-03-29",
  },
  {
    id: "90",
    userId: "user-90",
    name: "Shamar Joseph",
    displayName: "S Joseph",
    slug: "shamar-joseph",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Baracara",
    state: "Guyana",
    birthDate: "1999-08-31",
  },

  // ========== Ireland ==========

  {
    id: "91",
    userId: "user-91",
    name: "Paul Stirling",
    displayName: "P Stirling",
    slug: "paul-stirling",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Belfast",
    state: "Antrim",
    birthDate: "1990-09-03",
  },
  {
    id: "92",
    userId: "user-92",
    name: "Andrew Balbirnie",
    displayName: "A Balbirnie",
    slug: "andrew-balbirnie",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1990-12-28",
  },
  {
    id: "93",
    userId: "user-93",
    name: "Harry Tector",
    displayName: "H Tector",
    slug: "harry-tector",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_OFF_SPIN,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1999-12-06",
  },
  {
    id: "94",
    userId: "user-94",
    name: "Lorcan Tucker",
    displayName: "L Tucker",
    slug: "lorcan-tucker",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1996-09-10",
  },
  {
    id: "95",
    userId: "user-95",
    name: "Curtis Campher",
    displayName: "C Campher",
    slug: "curtis-campher",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Johannesburg",
    state: "Munster",
    birthDate: "1999-04-20",
  },
  {
    id: "96",
    userId: "user-96",
    name: "George Dockrell",
    displayName: "G Dockrell",
    slug: "george-dockrell",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_OFF_SPIN,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1992-07-22",
  },
  {
    id: "97",
    userId: "user-97",
    name: "Mark Adair",
    displayName: "M Adair",
    slug: "mark-adair",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Holywood",
    state: "Northern Cricket Union",
    birthDate: "1996-03-27",
  },
  {
    id: "98",
    userId: "user-98",
    name: "Gareth Delany",
    displayName: "G Delany",
    slug: "gareth-delany",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1997-04-28",
  },
  {
    id: "99",
    userId: "user-99",
    name: "Josh Little",
    displayName: "J Little",
    slug: "josh-little",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_FAST,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1999-11-01",
  },
  {
    id: "100",
    userId: "user-100",
    name: "Craig Young",
    displayName: "C Young",
    slug: "craig-young",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_FAST,
    city: "Derry",
    state: "North West",
    birthDate: "1990-04-04",
  },
  {
    id: "101",
    userId: "user-101",
    name: "Barry McCarthy",
    displayName: "B McCarthy",
    slug: "barry-mccarthy",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Dublin",
    state: "Leinster",
    birthDate: "1992-09-13",
  },
  {
    id: "102",
    userId: "user-102",
    name: "Benjamin White",
    displayName: "B White",
    slug: "benjamin-white",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_LEG_SPIN,
    city: "Dublin",
    state: "Northern Cricket Union",
    birthDate: "1998-08-29",
  },
  {
    id: "103",
    userId: "user-103",
    name: "Graham Hume",
    displayName: "G Hume",
    slug: "graham-hume",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM_FAST,
    city: "Johannesburg",
    state: "North West",
    birthDate: "1990-11-23",
  },
];

export default players;
