import {
  BattingStyle,
  BowlingStyle,
  PlayerRole,
} from "../../src/generated/prisma/enums.js";

export type playerType = {
  id: string;
  userId: string;
  name: string;
  displayName: string | null;
  slug: string;
  photoUrl: string | null;
  role: PlayerRole;
  canKeepWickets: boolean;
  battingStyle: BattingStyle;
  bowlingStyle: BowlingStyle;
  city: string;
  state: string;
  birthDate: string;
};

const players: playerType[] = [
  // ========== India ==========

  {
    id: "1",
    userId: "user-1",
    name: "Rohit Sharma",
    displayName: "R Sharma",
    slug: "rohit-sharma",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Mumbai",
    state: "Maharashtra",
    birthDate: "1987-04-30",
  },
  {
    id: "2",
    userId: "user-2",
    name: "Shikhar Dhawan",
    displayName: "S Dhawan",
    slug: "shikhar-dhawan",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Delhi",
    state: "Delhi",
    birthDate: "1985-12-05",
  },
  {
    id: "3",
    userId: "user-3",
    name: "Virat Kohli",
    displayName: "V Kohli",
    slug: "virat-kohli",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Delhi",
    state: "Delhi",
    birthDate: "1988-11-05",
  },
  {
    id: "4",
    userId: "user-4",
    name: "KL Rahul",
    displayName: "KL Rahul",
    slug: "kl-rahul",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Mangalore",
    state: "Karnataka",
    birthDate: "1992-04-18",
  },
  {
    id: "5",
    userId: "user-5",
    name: "Shreyas Iyer",
    displayName: "S Iyer",
    slug: "shreyas-iyer",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Mumbai",
    state: "Maharashtra",
    birthDate: "1994-12-06",
  },
  {
    id: "6",
    userId: "user-6",
    name: "Mahendra Singh Dhoni",
    displayName: "MS Dhoni",
    slug: "mahendra-singh-dhoni",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Ranchi",
    state: "Jharkhand",
    birthDate: "1981-07-07",
  },
  {
    id: "7",
    userId: "user-7",
    name: "Ravindra Jadeja",
    displayName: "R Jadeja",
    slug: "ravindra-jadeja",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Navagam",
    state: "Gujarat",
    birthDate: "1988-12-02",
  },
  {
    id: "8",
    userId: "user-8",
    name: "Axar Patel",
    displayName: "A Patel",
    slug: "axar-patel",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Nadiad",
    state: "Gujarat",
    birthDate: "1994-01-20",
  },
  {
    id: "9",
    userId: "user-9",
    name: "Ravichandran Ashwin",
    displayName: "R Ashwin",
    slug: "ravichandran-ashwin",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Chennai",
    state: "Tamil Nadu",
    birthDate: "1986-09-17",
  },
  {
    id: "10",
    userId: "user-10",
    name: "Jasprit Bumrah",
    displayName: "J Bumrah",
    slug: "jasprit-bumrah",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Ahmedabad",
    state: "Gujarat",
    birthDate: "1993-12-06",
  },
  {
    id: "11",
    userId: "user-11",
    name: "Bhuvneshwar Kumar",
    displayName: "B Kumar",
    slug: "bhuvneshwar-kumar",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Meerut",
    state: "Uttar Pradesh",
    birthDate: "1990-02-05",
  },
  {
    id: "12",
    userId: "user-12",
    name: "Mohammed Shami",
    displayName: "M Shami",
    slug: "mohammed-shami",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Amarohi",
    state: "West Bengal",
    birthDate: "1990-09-03",
  },
  {
    id: "13",
    userId: "user-13",
    name: "Kuldeep Yadav",
    displayName: "K Yadav",
    slug: "kuldeep-yadav",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.LEFT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.LEFT_ARM_MEDIUM,
    city: "Kanpur",
    state: "Uttar Pradesh",
    birthDate: "1994-12-14",
  },

  // ========== England ==========

  {
    id: "14",
    userId: "user-14",
    name: "Phil Salt",
    displayName: "P Salt",
    slug: "phil-salt",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Surrey",
    state: "England",
    birthDate: "1997-06-22",
  },
  {
    id: "15",
    userId: "user-15",
    name: "Jos Buttler",
    displayName: "J Buttler",
    slug: "jos-buttler",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: true,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Taunton",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "16",
    userId: "user-16",
    name: "Joe Root",
    displayName: "J Root",
    slug: "joe-root",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "17",
    userId: "user-17",
    name: "Jacob Bethell",
    displayName: "J Bethell",
    slug: "jacob-bethell",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "18",
    userId: "user-18",
    name: "Harry Brook",
    displayName: "H Brook",
    slug: "harry-brook",
    photoUrl: null,
    role: PlayerRole.BATSMAN,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "19",
    userId: "user-19",
    name: "Will Jacks",
    displayName: "W Jacks",
    slug: "will-jacks",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "20",
    userId: "user-20",
    name: "Ben Stokes",
    displayName: "B Stokes",
    slug: "ben-stokes",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "21",
    userId: "user-21",
    name: "Sam Curran",
    displayName: "S Curran",
    slug: "sam-curran",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "22",
    userId: "user-22",
    name: "Moeen Ali",
    displayName: "Moeen Ali",
    slug: "moeen-ali",
    photoUrl: null,
    role: PlayerRole.ALL_ROUNDER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "23",
    userId: "user-23",
    name: "Jofra Archer",
    displayName: "J Archer",
    slug: "jofra-archer",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "24",
    userId: "user-24",
    name: "Mark Wood",
    displayName: "M Wood",
    slug: "mark-wood",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
  {
    id: "25",
    userId: "user-25",
    name: "Chris Woakes",
    displayName: "C Woakes",
    slug: "chris-woakes",
    photoUrl: null,
    role: PlayerRole.BOWLER,
    canKeepWickets: false,
    battingStyle: BattingStyle.RIGHT_HANDED_BATSMAN,
    bowlingStyle: BowlingStyle.RIGHT_ARM_MEDIUM,
    city: "Sheffield",
    state: "England",
    birthDate: "1990-09-08",
  },
];

export default players;
