export type tournamentType = {
  id: string;
  organizationId: string;
  name: string;
  slug: string;
  logoUrl: string | null;
  city: string | null;
  state: string | null;
};

const tournaments: tournamentType[] = [
  {
    id: "tour-1",
    organizationId: "org-1",
    name: "Premier Cricket Championship",
    slug: "premier-cricket-championship",
    logoUrl: null,
    city: "Mumbai",
    state: "Maharashtra",
  },
  {
    id: "tour-2",
    organizationId: "org-1",
    name: "Champions T20 Trophy",
    slug: "champions-t20-trophy",
    logoUrl: null,
    city: "Bengaluru",
    state: "Karnataka",
  },
  {
    id: "tour-3",
    organizationId: "org-1",
    name: "National Super League",
    slug: "national-super-league",
    logoUrl: null,
    city: "New Delhi",
    state: "Delhi",
  },
  {
    id: "tour-4",
    organizationId: "org-1",
    name: "Royal Challenge Cup",
    slug: "royal-challenge-cup",
    logoUrl: null,
    city: "Jaipur",
    state: "Rajasthan",
  },
  {
    id: "tour-5",
    organizationId: "org-1",
    name: "Coastal Premier League",
    slug: "coastal-premier-league",
    logoUrl: null,
    city: "Chennai",
    state: "Tamil Nadu",
  },
  {
    id: "tour-6",
    organizationId: "org-1",
    name: "Deccan Gold Cup",
    slug: "deccan-gold-cup",
    logoUrl: null,
    city: "Hyderabad",
    state: "Telangana",
  },
  {
    id: "tour-7",
    organizationId: "org-1",
    name: "Heritage Cricket Carnival",
    slug: "heritage-cricket-carnival",
    logoUrl: null,
    city: "Kolkata",
    state: "West Bengal",
  },
  {
    id: "tour-8",
    organizationId: "org-1",
    name: "Western Giants Trophy",
    slug: "western-giants-trophy",
    logoUrl: null,
    city: "Ahmedabad",
    state: "Gujarat",
  },
  {
    id: "tour-9",
    organizationId: "org-1",
    name: "Northern Clash Championship",
    slug: "northern-clash-championship",
    logoUrl: null,
    city: "Chandigarh",
    state: "Punjab",
  },
  {
    id: "tour-10",
    organizationId: "org-1",
    name: "Central India Premier Cup",
    slug: "central-india-premier-cup",
    logoUrl: null,
    city: "Indore",
    state: "Madhya Pradesh",
  },
  {
    id: "tour-11",
    organizationId: "org-1",
    name: "Silicon City Cricket Bash",
    slug: "silicon-city-cricket-bash",
    logoUrl: null,
    city: "Pune",
    state: "Maharashtra",
  },
  {
    id: "tour-12",
    organizationId: "org-1",
    name: "Eastern Warriors Series",
    slug: "eastern-warriors-series",
    logoUrl: null,
    city: "Bhubaneswar",
    state: "Odisha",
  },
  {
    id: "tour-13",
    organizationId: "org-1",
    name: "Southern Derby Tournament",
    slug: "southern-derby-tournament",
    logoUrl: null,
    city: "Kochi",
    state: "Kerala",
  },
  {
    id: "tour-14",
    organizationId: "org-1",
    name: "Capital City Invitational",
    slug: "capital-city-invitational",
    logoUrl: null,
    city: "Lucknow",
    state: "Uttar Pradesh",
  },
  {
    id: "tour-15",
    organizationId: "org-1",
    name: "Himalayan Winter Cup",
    slug: "himalayan-winter-cup",
    logoUrl: null,
    city: "Dehradun",
    state: "Uttarakhand",
  },
  {
    id: "tour-16",
    organizationId: "org-1",
    name: "Bay Masters Cricket League",
    slug: "bay-masters-cricket-league",
    logoUrl: null,
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
  },
  {
    id: "tour-17",
    organizationId: "org-1",
    name: "Desert Classic Championship",
    slug: "desert-classic-championship",
    logoUrl: null,
    city: "Jodhpur",
    state: "Rajasthan",
  },
  {
    id: "tour-18",
    organizationId: "org-1",
    name: "Pride of Gujarat Trophy",
    slug: "pride-of-gujarat-trophy",
    logoUrl: null,
    city: "Surat",
    state: "Gujarat",
  },
  {
    id: "tour-19",
    organizationId: "org-1",
    name: "Northeast Rising Cup",
    slug: "northeast-rising-cup",
    logoUrl: null,
    city: "Guwahati",
    state: "Assam",
  },
  {
    id: "tour-20",
    organizationId: "org-1",
    name: "Grand Finale Super Cup",
    slug: "grand-finale-super-cup",
    logoUrl: null,
    city: "Nagpur",
    state: "Maharashtra",
  },
];

export default tournaments;
